# .github/workflows/unittests.yaml
name: Python Unit Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest # Or 'macos-latest', 'windows-latest'
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11"] # Test against different Python versions

    steps:
    - name: Checkout code
      uses: actions/checkout@v4 # Action to check out your repository code

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip' # Cache pip dependencies for faster builds

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        # If your 'src' folder is intended to be a package, you might also do:
        # pip install -e ./src

    - name: Run unit tests
      run: |
        # pytest is a common testing framework. Install it if not in requirements.txt.
        # pip install pytest
        # The -v (verbose) and -s (no capture) flags are common.
        # The 'tests' argument tells pytest where to find tests.
        pytest -v -s tests/